languageCode = "en-us"
title = "Texter"
baseURL = "https://Robok3000.github.io/cupper/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Repositorio de historias absurdas universales"
  codePenUser = "Heydon"
