languageCode = "en-us"
title = "Texter"
baseURL = "https://robok3000.github.io/cupper/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Repositorio de crónicas urbanas basadas en Latinoamérica"
  codePenUser = "Heydon"
